options:
  auto-update: true

# Tim tat ca loai quai tai: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
mobs:
  - AXOLOTL
  - BAT
  - BEE
  - BLAZE
  - CAT
  - CAVE_SPIDER
  - CHICKEN
  - COD
  - COW
  - CREEPER
  - DOLPHIN
  - DONKEY
  - DROWNED
  - ELDER_GUARDIAN
  - ENDERMAN
  - ENDERMITE
  - EVOKER
  - EVOKER_FANGS
  - FOX
  - GHAST
  - GIANT
  - GLOW_SQUID
  - GOAT
  - GUARDIAN
  - HOGLIN
  - HORSE
  - HUSK
  - ILLUSIONER
  - IRON_GOLEM
  - LLAMA
  - MAGMA_CUBE
  - MULE
  - MUSHROOM_COW
  - OCELOT
  - PANDA
  - PARROT
  - PHANTOM
  - PIG
  - PIGLIN
  - PIGLIN_BRUTE
  - PILLAGER
  - POLAR_BEAR
  - PUFFERFISH
  - RABBIT
  - RAVAGER
  - SALMON
  - SHEEP
  - SILVERFISH
  - SKELETON
  - SLIME
  - SNOWMAN
  - SPIDER
  - SQUID
  - STRAY
  - STRIDER
  - TRADER_LLAMA
  - TURTLE
  - VEX
  - VILLAGER
  - VINDICATOR
  - WITCH
  - WITHER_SKELETON
  - WOLF
  - ZOGLIN
  - ZOMBIE
  - ZOMBIE_VILLAGER
  - ZOMBIFIED_PIGLIN
